export const FETCHING_POPULAR_MOVIES_REQUEST =
  'FETCHING_POPULAR_MOVIES_REQUEST';
export const FETCHING_POPULAR_MOVIES_SUCCESS =
  'FETCHING_POPULAR_MOVIES_SUCCESS';
export const FETCHING_POPULAR_MOVIES_FAILURE =
  'FETCHING_POPULAR_MOVIES_FAILURE';
export const FETCHING_MOVIE_REQUEST = 'FETCHING_MOVIE_REQUEST';
export const FETCHING_MOVIE_SUCCESS = 'FETCHING_MOVIE_SUCCESS';
export const FETCHING_MOVIE_FAILURE = 'FETCHING_MOVIE_FAILURE';
export const FETCHING_MOVIE_CREDITS_REQUEST = 'FETCHING_MOVIE_CREDITS_REQUEST';
export const FETCHING_MOVIE_CREDITS_SUCCESS = 'FETCHING_MOVIE_CREDITS_SUCCESS';
export const FETCHING_MOVIE_CREDITS_FAILURE = 'FETCHING_MOVIE_CREDITS_FAILURE';
